name: Compilar APK JavaFX Gluon

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar GraalVM para Gluon
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Aumentar memoria Swap
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Compilar APK JavaFX con detalles de error
        run: |
          cd RelojDigital
          chmod +x mvnw
          ./mvnw clean gluonfx:build gluonfx:package -Pandroid -e

      - name: Subir APK final
        uses: actions/upload-artifact@v4
        with:
          name: app-reloj-digital-javafx
          path: RelojDigital/target/gluonfx/aarch64-android/gvm/*.apk
